package:
  name: funcdesigner
  version: "0.5620"

source:
  fn: FuncDesigner-0.5620.tar.gz
  url: https://pypi.python.org/packages/source/F/FuncDesigner/FuncDesigner-0.5620.tar.gz
  md5: 413813cd62029b9d9156c5085949d694
  patches:
    - fix_generator35.patch

build:
  number: {{ environ.get("APPVEYOR_BUILD_NUMBER", 1) }} [win]
  number: {{ environ.get("TRAVIS_BUILD_NUMBER", 1) }} [osx or linux]

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy

  run:
    - python
    - numpy
    - scipy

test:
  # Python imports
  imports:
    - FuncDesigner
    - FuncDesigner.examples

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://openopt.org
  license: BSD License
  summary: 'A python module for function design and automatic derivatives'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
