language: generic

os:
  - osx
  - linux

env:
  matrix:
    - PYTHON=3.5
  global:
    secure: eGCijJbVIN09JXeM6uRKYClqYa97hxXAb4gWdnDSChglvqQQlcINsOJw5rEgowIOgPwYR5pRDXa5lDs68hvdpxHHTw6dVRX2X4XdkILYJhP/plpkZIPoWEOsAnNoehMDtZKZlT4NFg30xVHmdE7bV//vkPjeHKVpiKAp/M2SgimNbRz1v8mAgFddQjXUOaqe6Cn5/hNBMhnn6eibsdHMGv9VRllbCCQvWptKmvEZ75IUpS+/58dsyimf5isj7Kn5bgNYFc/vglmM+gsr6QiGxcKH1xLorXuGNu4S9hV3rHs15X9Fj6eOLsNTC/l7HvzvMW3CeGuuhnqs89uEPBKIFXOUEBCyLL6ujTJDf0WpZiEICfpFPws4T20SiWJVMxLJRZnpmMmhKyg6d7qvi3yBSzb4sqxxVrgkw5IT5IlPkgI+rNCnIdnwJtaSQTR2BBuj58HvUyRkwrDZbrVjmVorPVly1z1cCxAIGTKIeDD+LKfm1ouS/8cl7HftSIqc3QhiqWjxTOOLRv5rnJqgMtwZMgaOVQ/rx77rBKqbvnCvPMKBc58oL6RglYvtP1giq6t2yTwWmUUjkcR36Ess+JwZ1EznaXhEVsk4zeBueVfiHvBlBxrgvvdXZ5DjdwrcCFjRScQOMKUwwBPtMk0GcG0d73Klbr1h+OctcUfwg4TCAk8=

branches:
  only:
    - osx-travis

before_install:
  # Operative system
  - if [[ "$(uname)" == "Darwin" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - if [[ "$(uname)" == "Linux" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Install the build and runtime dependencies of the project
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -q conda-build anaconda-client
  - conda info -a

  # Check that we have the expected version of Python
  - python --version

install:
  - conda build -q pyutilib serpent pyro4 pyomo --python $PYTHON
  - conda build -q suds-jurko setproctitle openopt funcdesigner derapproximator pyomo.extras --python $PYTHON
  - conda build -q ipopt_bin --python $PYTHON
  - conda build -q glpk --python $PYTHON || true

script:
  - echo "XXX Test here XXX"

after_success:
  - anaconda -t $BINSTAR_TOKEN upload --no-progress $HOME/miniconda/conda-bld/osx/*.tar.bz2

sudo: false
