# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

version: 0.1b1-{build}

branches:
  only:
  - master

environment:
  BINSTAR_TOKEN:
    secure: n7ll7JzU0nTN2caHJWRj0IflEN66ZIYwbMzexr6G2U7njzVdOY5Uvn17UZdhebq8

  matrix:
    - PYTHON: 3.5

install:
  - "set PATH=C:\\Miniconda3-x64;C:\\Miniconda3-x64\\Scripts;%PATH%"

  # Install the build and runtime dependencies of the project.
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda config --add channels conda-forge"
  - "conda update -q conda"
  - "conda install -q conda-build anaconda-client"
  - "conda info -a"

  # Check that we have the expected version of Python
  - "python --version"

build: off

before_test:
  - "conda build -q pyutilib serpent pyro4 pyomo --python %PYTHON%"
  - "conda build -q openopt funcdesigner derapproximator pyomo.extras --python %PYTHON%"
  - "conda build -q ipopt_bin --python %PYTHON%"

# Actual test here
test_script:
  - "echo XXX Test here XXX"

after_test:
  - "anaconda -t %BINSTAR_TOKEN% upload --no-progress C:\\Miniconda3-x64\\conda-bld\\win-64\\*.tar.bz2"
