package:
  name: suds-jurko
  version: "0.6"

source:
  fn: suds-jurko-0.6.tar.bz2
  url: https://pypi.python.org/packages/source/s/suds-jurko/suds-jurko-0.6.tar.bz2
  md5: 1309e9bc2454aa3434041f0a24ae4e11

build:
  number: {{ environ.get("APPVEYOR_BUILD_NUMBER", 1) }} [win]
  number: {{ environ.get("TRAVIS_BUILD_NUMBER", 1) }} [osx or linux]

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - suds
    - suds.bindings
    - suds.mx
    - suds.sax
    - suds.transport
    - suds.umx
    - suds.xsd
    - tests
    - tests.external

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - pytest
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bitbucket.org/jurko/suds
  license: GNU Library or Lesser General Public License (LGPL)
  summary: "Lightweight SOAP client (Jurko's fork)"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
