package:
  name: setproctitle
  version: "1.1.9"

source:
  fn: setproctitle-1.1.9.tar.gz
  url: https://pypi.python.org/packages/source/s/setproctitle/setproctitle-1.1.9.tar.gz
  md5: 95d9e56c69437246460a20804961d70d

build:
  number: {{ environ.get(APPVEYOR_BUILD_NUMBER, 1) }} [win]

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - setproctitle

about:
  home: https://github.com/dvarrazzo/py-setproctitle
  license: BSD License
  summary: 'A Python module to customize the process title'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
