package:
  name: serpent
  version: "1.12"

source:
  fn: serpent-1.12.tar.gz
  url: https://pypi.python.org/packages/source/s/serpent/serpent-1.12.tar.gz
  md5: 05869ac7b062828b34f8f927f0457b65

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  license: MIT License
  summary: 'Serialization based on ast.literal_eval'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
