package:
  name: appdirs
  version: "1.4.0"

source:
  fn: appdirs-1.4.0.tar.gz
  url: https://pypi.python.org/packages/source/a/appdirs/appdirs-1.4.0.tar.gz
  md5: 1d17b4c9694ab84794e228f28dc3275b

build:
  noarch_python: True
  number: {{ environ.get("APPVEYOR_BUILD_NUMBER", 1) }} [win]
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/ActiveState/appdirs
  license: MIT License
  summary: 'A small Python module for determining appropriate " +         "platform-specific dirs, e.g. a "user data dir".'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
