package:
  name: pyomo.extras
  version: 3.0

build:
  noarch_python: True

requirements:
  run:
    - python
    - sympy
    - xlrd
    - openpyxl
    - suds-jurko
    - pyyaml
    - pypyodbc
    - pymysql
    - openopt
    - funcdesigner
    - derapproximator
    - ipython
    - pyro4

about:
  license: BSD License
  summary: 'Extra Python packages that enhance the functionality of Pyomo'
